const WORDS=['BELOW','COLD','WAIT','HELP','RUN','LOOK','BURIED','ASH','BONE','DARK','LEAVE','NOW','HERE','LOST','RISE','SEEK','PRAY','WATCH','BEHIND','STONE','NAME','FORGOT','LISTEN','SPEAK','TOUCH','EMPTY','ALONE'];
const state={mode:'dashboard',live:false,raf:0,wordTimer:0,audioCtx:null,analyser:null,data:null,audioStream:null,cameraStream:null,geoWatch:null,rf:[],words:[],touch:0,s:{x:0,y:0,z:0,mag:0,audio:0,gps:null,battery:null,drain:0,temp:22.5,pressure:1013,humidity:65,rfNoise:0,rfAvg:0,light:null,lightDelta:0}};
const $=id=>document.getElementById(id);
const els={engage:$('engageBtn'),recal:$('recalibrateBtn'),close:$('closeVisualBtn'),status:$('permissionStatus'),badge:$('systemBadge'),canvas:$('meterCanvas'),video:$('cameraFeed'),flash:$('flashOverlay'),target:$('visualTarget'),camHud:$('cameraHud'),modeLabel:$('modeLabel'),spirit:$('spiritBox'),telemetry:$('telemetryLog'),drain:$('drainRateValue'),emf:$('emfValue'),emfBar:$('emfBar'),audio:$('audioValue'),audioBar:$('audioBar'),touch:$('touchValue'),touchBar:$('touchBar'),rf:$('rfValue'),rfBar:$('rfBar'),battery:$('batteryValue'),batteryBar:$('batteryBar'),temp:$('tempValue'),tempBar:$('tempBar'),orientation:$('orientationValue'),gps:$('gpsValue'),humidity:$('humidityValue'),light:$('lightValue'),snap:$('snapBtn'),modes:[...document.querySelectorAll('.mode-button')]};
const ctx=els.canvas.getContext('2d'); const lightCanvas=document.createElement('canvas'); lightCanvas.width=32; lightCanvas.height=32; const lightCtx=lightCanvas.getContext('2d',{willReadFrequently:true});
let telemetry=[['System','Awaiting calibration'],['Mobile','Standalone page ready']];
function log(k,v){telemetry=[[k,v],...telemetry].slice(0,8); els.telemetry.innerHTML=telemetry.map(([a,b])=>`<li><span>${a}</span><span>${b}</span></li>`).join('');}
function setBadge(text,live){els.badge.textContent=text; els.badge.classList.toggle('status-live',!!live); els.badge.classList.toggle('status-idle',!live);} 
function pct(n){return Math.max(0,Math.min(100,n));}
function bar(el,v){el.style.width=`${pct(v)}%`;}
function setMode(mode){state.mode=mode; els.modes.forEach(b=>b.classList.toggle('is-active',b.dataset.mode===mode)); els.modeLabel.textContent=`MODE: ${mode.toUpperCase()}`; const visual=mode==='visual'; els.target.classList.toggle('hidden',!visual); els.video.classList.toggle('is-visible',visual&&!!state.cameraStream); if(visual) startCamera(); else stopCamera(); log('Mode',mode.toUpperCase());}
async function motionPermission(){if(typeof DeviceMotionEvent!=='undefined'&&typeof DeviceMotionEvent.requestPermission==='function'){try{return(await DeviceMotionEvent.requestPermission())==='granted';}catch{return false;}} return true;}
async function startAudio(){try{state.audioStream=await navigator.mediaDevices.getUserMedia({audio:true}); const AC=window.AudioContext||window.webkitAudioContext; state.audioCtx=new AC(); state.analyser=state.audioCtx.createAnalyser(); state.analyser.fftSize=64; state.audioCtx.createMediaStreamSource(state.audioStream).connect(state.analyser); state.data=new Uint8Array(state.analyser.frequencyBinCount); log('Mic','Online'); return true;}catch{log('Mic','Unavailable'); return false;}}
async function startCamera(){if(state.cameraStream||!state.live) return; try{state.cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false}); els.video.srcObject=state.cameraStream; els.video.classList.add('is-visible'); log('Camera','Online');}catch{log('Camera','Unavailable');}}
function stopCamera(){if(state.cameraStream){state.cameraStream.getTracks().forEach(t=>t.stop()); state.cameraStream=null;} els.video.srcObject=null; els.video.classList.remove('is-visible');}
function stopAll(){if(state.audioStream){state.audioStream.getTracks().forEach(t=>t.stop()); state.audioStream=null;} if(state.audioCtx){state.audioCtx.close(); state.audioCtx=null;} if(state.geoWatch!=null&&navigator.geolocation){navigator.geolocation.clearWatch(state.geoWatch); state.geoWatch=null;} stopCamera(); cancelAnimationFrame(state.raf); clearInterval(state.wordTimer);} 
function handleMotion(e){state.s.x=e.accelerationIncludingGravity?.x??state.s.x; state.s.y=e.accelerationIncludingGravity?.y??state.s.y; state.s.z=e.accelerationIncludingGravity?.z??state.s.z;}
function handleOrientation(e){state.s.mag=e.alpha??state.s.mag;}
function attachSensors(){window.addEventListener('devicemotion',handleMotion,{passive:true}); window.addEventListener('deviceorientation',handleOrientation,{passive:true}); if(navigator.geolocation&&state.geoWatch==null){state.geoWatch=navigator.geolocation.watchPosition(p=>state.s.gps=p.coords.accuracy,()=>log('GPS','Unavailable'),{enableHighAccuracy:true,maximumAge:5000});}
 if(navigator.getBattery){navigator.getBattery().then(b=>{state.s.battery=b.level*100; b.addEventListener('levelchange',()=>state.s.battery=b.level*100); log('Battery','Available');}).catch(()=>log('Battery','Unavailable'));} else {log('Battery','Unsupported');}}
function touchForce(v){state.touch=Math.max(0,Math.min(1,v)); state.s.touch=state.touch; clearTimeout(state.touchReset); state.touchReset=setTimeout(()=>{state.touch=0; state.s.touch=0;},160);} 
function handleTouch(e){const t=e.touches[0]; if(!t) return; touchForce(typeof t.force==='number'&&t.force>0?t.force:Math.min(1,0.35+e.touches.length*0.15));}
function flash(){els.flash.classList.add('is-flashing'); setTimeout(()=>els.flash.classList.remove('is-flashing'),180);} 
function sampleAudio(){if(!state.analyser||!state.data) return; state.analyser.getByteFrequencyData(state.data); state.s.audio=state.data.reduce((a,b)=>a+b,0)/state.data.length;}
function env(frame){if(frame%50===0){const motion=(Math.abs(state.s.x)+Math.abs(state.s.y)+Math.abs(state.s.z))/30; state.s.temp+=(Math.random()-.5)*.12-motion*.04; state.s.pressure+=(Math.random()-.5)*.8; state.s.humidity=Math.max(0,Math.min(100,state.s.humidity+(Math.random()-.5)*1.2));}
const raw=Math.random()*100; state.rf.push(raw); if(state.rf.length>10) state.rf.shift(); state.s.rfNoise=raw; state.s.rfAvg=state.rf.reduce((a,b)=>a+b,0)/state.rf.length; if(state.s.battery!=null&&frame%60===0){const stress=(Math.abs(state.s.x)+Math.abs(state.s.y)+Math.abs(state.s.z))/20; state.s.drain=Math.max(.01,.01+((Math.random()-.42)*.05*stress))*100;}}
function sampleLight(frame){if(state.mode!=='visual'||!lightCtx||!state.cameraStream||frame%10!==0||!els.video.videoWidth) return; try{lightCtx.drawImage(els.video,0,0,32,32); const img=lightCtx.getImageData(0,0,32,32); let total=0; for(let i=0;i<img.data.length;i+=4) total+=(img.data[i]+img.data[i+1]+img.data[i+2])/3; const level=total/(32*32)/255*100; state.s.lightDelta=state.s.light==null?0:level-state.s.light; state.s.light=level;}catch{}}
function renderReadings(){const motion=Math.abs(state.s.x)+Math.abs(state.s.y)+Math.abs(state.s.z); const emf=Math.round(motion*3.4); const aud=(state.s.audio/255)*100; const touch=(state.s.touch||0)*100; const rf=state.s.rfAvg; const batt=state.s.battery==null?0:state.s.battery; const temp=((state.s.temp-10)/30)*100; els.emf.textContent=`${emf} mG`; els.audio.textContent=`${Math.round(aud)} dB`; els.touch.textContent=`${Math.round(touch)} %`; els.rf.textContent=`${Math.round(state.s.rfAvg*1.5)} p/s`; els.battery.textContent=state.s.battery==null?'N/A':`${Math.round(state.s.battery)}% · ${state.s.drain.toFixed(2)}%/min`; els.temp.textContent=`${state.s.temp.toFixed(1)}°C · ${Math.round(state.s.pressure)} hPa`; els.orientation.textContent=`${Math.round(state.s.mag||0)}°`; els.gps.textContent=state.s.gps==null?'N/A':`${Math.round(state.s.gps)} m`; els.humidity.textContent=`${Math.round(state.s.humidity)}%`; els.light.textContent=state.s.light==null?'N/A':`${Math.round(state.s.light)}% (${state.s.lightDelta>=0?'+':''}${state.s.lightDelta.toFixed(1)})`; els.camHud.textContent=state.s.light==null?'LIGHT: --':`LIGHT: ${Math.round(state.s.light)}%`; els.drain.textContent=`Drain: ${state.s.drain.toFixed(2)}%/min`; bar(els.emfBar,emf); bar(els.audioBar,aud); bar(els.touchBar,touch); bar(els.rfBar,rf); bar(els.batteryBar,batt); bar(els.tempBar,temp);} 
function draw(frame){const rect=els.canvas.getBoundingClientRect(); const ratio=window.devicePixelRatio||1; const w=Math.max(320,Math.floor(rect.width*ratio)); const h=Math.max(220,Math.floor(rect.height*ratio)); if(els.canvas.width!==w||els.canvas.height!==h){els.canvas.width=w; els.canvas.height=h;} ctx.clearRect(0,0,w,h); ctx.fillStyle='rgba(2,5,10,.92)'; ctx.fillRect(0,0,w,h); const motion=Math.abs(state.s.x)+Math.abs(state.s.y)+Math.abs(state.s.z); const intensity=Math.min(1,(motion/25)+(state.s.audio/255)+((state.s.touch||0)*.5));
 if(state.mode==='dashboard'){ctx.strokeStyle=intensity>.7?'#ff5f6d':intensity>.4?'#ffd45c':'#3fda8b'; ctx.lineWidth=2*ratio; ctx.beginPath(); const bins=state.data||new Uint8Array(32); const slice=w/bins.length; for(let i=0;i<bins.length;i++){const y=(bins[i]/255)*h; const x=i*slice; if(i===0) ctx.moveTo(x,y); else ctx.lineTo(x,y);} ctx.stroke();}
 else if(state.mode==='spectral'){ctx.strokeStyle=intensity>.65?'#ffb020':'#69c7ff'; ctx.lineWidth=2.4*ratio; ctx.beginPath(); for(let i=0;i<w;i+=6){const y=(h/2)+Math.sin((i/18)+frame*.06)*(24*ratio*Math.max(.25,intensity))+(Math.random()-.5)*(state.s.audio/8); if(i===0) ctx.moveTo(i,y); else ctx.lineTo(i,y);} ctx.stroke();}
 else if(state.mode==='rf'){const bw=Math.max(4*ratio,w/48); for(let x=0;x<w;x+=bw+1){const wave=Math.sin(frame*.08+x/40)*.5+.5; const signal=wave*.6+Math.random()*.4; const bh=signal*h*.85; ctx.fillStyle=`hsla(${195+signal*110},90%,58%,.88)`; ctx.fillRect(x,h-bh,bw,bh);} ctx.strokeStyle='rgba(255,255,255,.12)'; ctx.beginPath(); ctx.moveTo(0,h*.25); ctx.lineTo(w,h*.25); ctx.moveTo(0,h*.5); ctx.lineTo(w,h*.5); ctx.moveTo(0,h*.75); ctx.lineTo(w,h*.75); ctx.stroke();}
 else if(state.mode==='visual'){ctx.strokeStyle=motion<12?'rgba(119,255,176,.92)':'rgba(255,212,92,.92)'; ctx.lineWidth=2*ratio; const size=72*ratio, cx=w/2, cy=h/2, x=cx-size/2, y=cy-size/2, c=18*ratio; ctx.beginPath(); ctx.moveTo(x,y+c); ctx.lineTo(x,y); ctx.lineTo(x+c,y); ctx.moveTo(x+size-c,y); ctx.lineTo(x+size,y); ctx.lineTo(x+size,y+c); ctx.moveTo(x,y+size-c); ctx.lineTo(x,y+size); ctx.lineTo(x+c,y+size); ctx.moveTo(x+size-c,y+size); ctx.lineTo(x+size,y+size); ctx.lineTo(x+size,y+size-c); ctx.stroke();}}
function renderWords(){els.spirit.querySelectorAll('.spirit-word').forEach(n=>n.remove()); const empty=els.spirit.querySelector('.spirit-empty'); if(!state.words.length){empty?.classList.remove('hidden'); return;} empty?.classList.add('hidden'); state.words.forEach((word,index)=>{const div=document.createElement('div'); div.className='spirit-word'; div.textContent=word.text; div.style.transform=`translate(calc(-50% + ${word.x}px), calc(-50% + ${index*26}px)) scale(${Math.max(.55,1-index*.12)*word.i})`; div.style.opacity=Math.max(.15,1-index*.18); div.style.filter=`blur(${index*1.5}px)`; div.style.color=word.i>1.7?'#ffdb85':'#f3f6fb'; div.style.textShadow=`0 0 ${8*word.i}px rgba(255,255,255,.45)`; els.spirit.appendChild(div);});}
function maybeWord(){if(!state.live||state.mode==='visual') return; const total=Math.sqrt((state.s.x**2)+(state.s.y**2)+(state.s.z**2)); const motion=Math.min(Math.abs(total-9.8)/5,1); const audio=Math.min(state.s.audio/100,1); const rf=state.s.rfNoise>85?1:0; let p=.02+(motion*.4)+(audio*.5)+(rf*.3); if(p>.8||Math.random()<p){const i=Math.min(2.4,.8+motion+audio+((state.s.touch||0)*.6)); state.words=[{text:WORDS[Math.floor(Math.random()*WORDS.length)],x:(Math.random()-.5)*130,i},...state.words].slice(0,6); renderWords(); if(navigator.vibrate) navigator.vibrate(Math.floor(45+i*75));}}
function loop(){let frame=0; const tick=()=>{frame++; sampleAudio(); env(frame); sampleLight(frame); draw(frame); renderReadings(); state.raf=requestAnimationFrame(tick);}; state.raf=requestAnimationFrame(tick);} 
async function engage(){els.status.innerHTML='Requesting permissions and calibrating mobile sensors...'; setBadge('Calibrating',true); stopAll(); const motion=await motionPermission(); const audio=await startAudio(); attachSensors(); state.live=true; loop(); state.wordTimer=setInterval(maybeWord,500); renderWords(); renderReadings(); els.status.innerHTML=`System active: ${audio?'microphone online':'microphone unavailable'}, ${motion?'motion online':'motion unavailable'}, location optional.`; setBadge('Live',true); log('System','Field meter engaged');}
function recalibrate(){state.words=[]; state.rf=[]; Object.assign(state.s,{x:0,y:0,z:0,mag:0,audio:0,drain:0,temp:22.5,pressure:1013,humidity:65,rfNoise:0,rfAvg:0,light:null,lightDelta:0}); renderWords(); renderReadings(); log('System','Manual recalibration complete');}
function init(){els.engage.addEventListener('click',engage); els.recal.addEventListener('click',recalibrate); els.close.addEventListener('click',()=>state.mode==='visual'&&setMode('dashboard')); els.snap.addEventListener('click',flash); els.modes.forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode))); window.addEventListener('touchstart',handleTouch,{passive:true}); window.addEventListener('touchmove',handleTouch,{passive:true}); window.addEventListener('touchend',()=>touchForce(0),{passive:true}); window.addEventListener('beforeunload',stopAll); renderReadings(); log('Sensors','Tap Engage System'); renderWords();}
init();