const $ = id => document.getElementById(id);

export const els = {
  engage: $('engageBtn'),
  recal: $('recalibrateBtn'),
  close: $('closeVisualBtn'),
  settings: $('settingsBtn'),
  install: $('installBtn'),
  power: $('powerModeBtn'),
  exportBtn: $('exportBtn'),
  permission: $('permissionStatus'),
  permissionDrawer: $('permissionDrawer'),
  badge: $('systemBadge'),
  canvas: $('meterCanvas'),
  video: $('cameraFeed'),
  flash: $('flashOverlay'),
  target: $('visualTarget'),
  visualLockText: $('visualLockText'),
  camHud: $('cameraHud'),
  modeLabel: $('modeLabel'),
  spirit: $('spiritBox'),
  telemetry: $('telemetryLog'),
  timeline: $('timelineList'),
  timelineSummary: $('timelineSummary'),
  drain: $('drainRateValue'),
  emf: $('emfValue'),
  emfBar: $('emfBar'),
  emfPeak: $('emfPeak'),
  audio: $('audioValue'),
  audioBar: $('audioBar'),
  audioPeak: $('audioPeak'),
  touch: $('touchValue'),
  touchBar: $('touchBar'),
  touchPeak: $('touchPeak'),
  rf: $('rfValue'),
  rfBar: $('rfBar'),
  rfPeak: $('rfPeak'),
  battery: $('batteryValue'),
  batteryBar: $('batteryBar'),
  batteryPeak: $('batteryPeak'),
  anomaly: $('anomalyValue'),
  anomalyBar: $('anomalyBar'),
  anomalyMeta: $('anomalyMeta'),
  temp: $('tempValue'),
  tempBar: $('tempBar'),
  orientation: $('orientationValue'),
  gps: $('gpsValue'),
  humidity: $('humidityValue'),
  light: $('lightValue'),
  snap: $('snapBtn'),
  sensorChips: $('sensorChips'),
  toggleTelemetry: $('toggleTelemetryBtn'),
  diagnostics: $('diagnosticsPanel'),
  viewport: $('viewportPanel'),
  profileSelect: $('profileSelect'),
  presetSelect: $('presetSelect'),
  exportFormatSelect: $('exportFormatSelect'),
  modes: [...document.querySelectorAll('.mode-button')],
};

export const ctx = els.canvas.getContext('2d');
export const lightCanvas = document.createElement('canvas');
lightCanvas.width = 32;
lightCanvas.height = 32;
export const lightCtx = lightCanvas.getContext('2d', { willReadFrequently: true });
