export const WORDS = ['BELOW','COLD','WAIT','HELP','RUN','LOOK','BURIED','ASH','BONE','DARK','LEAVE','NOW','HERE','LOST','RISE','SEEK','PRAY','WATCH','BEHIND','STONE','NAME','FORGOT','LISTEN','SPEAK','TOUCH','EMPTY','ALONE'];
export const SENSOR_KEYS = ['mic','motion','camera','gps','battery','touch'];
export const TELEMETRY_LIMIT = 16;

export const state = {
  live: false,
  mode: 'dashboard',
  lowPower: false,
  diagnosticsCollapsed: false,
  hiddenPaused: false,
  frame: 0,
  raf: 0,
  wordTimer: 0,
  resizeObserver: null,
  audioCtx: null,
  analyser: null,
  data: null,
  audioStream: null,
  cameraStream: null,
  batteryManager: null,
  batteryListener: null,
  geoWatch: null,
  sensorsAttached: false,
  canvasSize: { width: 900, height: 420, ratio: 1 },
  rf: [],
  words: [],
  sessionEvents: [],
  touchReset: 0,
  telemetry: [
    ['System', 'Awaiting calibration'],
    ['Mobile', 'Standalone page ready'],
  ],
  status: {
    mic: 'idle',
    motion: 'idle',
    camera: 'idle',
    gps: 'idle',
    battery: 'idle',
    touch: 'proxy',
  },
  s: {
    x: 0,
    y: 0,
    z: 0,
    mag: 0,
    audio: 0,
    gps: null,
    battery: null,
    drain: 0,
    temp: 22.5,
    pressure: 1013,
    humidity: 65,
    rfNoise: 0,
    rfAvg: 0,
    light: null,
    lightDelta: 0,
    touch: 0,
  },
};
